### ISSUE TITLE
Error Message on com_agosms version 1.0.46

### ISSUE THREAD

**Issue by jojo12** [astridx/plg_fields_agosmmapwithmarker#5]
Warning: count(): Parameter must be an array or an object that implements Countable in /srv/www/vhosts/mysite.ch/httpdocs/components/com_agosms/models/categories.php on line 96

**Comment by astridx** [comment]
Is this the right issue here, or did you want to open it in the other repo https://github.com/astridx/pkg_agosms/issues?

**Comment by jojo12** [comment]
Sorry, I think I made a mix. Can be closed
